import { TAG_CARD_DATA, THESIS_LINKS } from './background';
import { PROFILE } from './profile';
import { SKILLS_SECTIONS } from './skills';

const SELECTED_SKILLS = new Set([
  'TypeScript',
  'JavaScript',
  'HTML',
  'CSS',
  'React',
  'Angular',
  'Express',
  'NestJS',
  'Tailwind CSS',
  'Material UI',
  'Redux',
  'MobX',
  'RxJS',
  'NgRx',
  'Node.js',
  'Bun',
  'ESLint',
  'Prettier',
  'Vite',
  'Webpack',
  'Jest',
  'Vitest',
  'Storybook',
  'Docker',
  'Bash',
  'PostgreSQL',
  'MySQL',
  'MongoDB',
  'GitHub Actions',
  'Codex CLI',
  'Copilot',
  'Windows',
  'macOS',
  'Linux',
  'Kotlin',
  'Java',
  'C#',
  'C++',
  'Spring Boot',
  'JPA/Hibernate',
  'Liquibase',
  'Vue',
  'AngularJS',
  'ASP.NET MVC',
  'ASP.NET Web Forms',
  'WPF',
  'Windows Forms',
  'JVM',
  '.NET Framework',
  'React Testing Library',
  'Mocha',
  'Nx (monorepo)',
  'Prisma',
  'Maven',
  'JUnit',
  'H2',
  'SQLite',
  'Microsoft SQL Server',
  'Ruby',
  'Python',
  'GraphQL',
  'Android SDK',
  'Playwright',
  'Cypress',
  'IBM DB2',
  'Oracle Database',
  'Claude',
  'Cursor',
]);

export const DETAILED_CV = {
  summary: [PROFILE.availability, PROFILE.services],
  skills: SKILLS_SECTIONS.map((section) => ({
    ...section,
    groups: section.groups
      .filter((group) => !['Source Control', 'IDEs'].includes(group.title))
      .map((group) => ({
        ...group,
        skills: group.skills.filter((skill) => SELECTED_SKILLS.has(skill)),
      }))
      .filter((group) => group.skills.length > 0),
  })),
  languages: TAG_CARD_DATA.find((group) => group.title === 'Languages')?.tags ?? [],
  thesisLinks: THESIS_LINKS.filter((item) =>
    ['Thesis summary on the faculty site', 'Thesis application source code'].includes(item.label),
  ),
} as const;
